default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: app-frogmi

test:
  <<: *default
  database: app-frogmi

# production:
#   <<: *default
#   database: your_app_name_production
#   username: your_production_username
#   password: your_production_password
